#! /bin/sh
### BEGIN INIT INFO
# Provides:          presto-server
# Required-Start:    $network $named $remote_fs $syslog
# Required-Stop:     $network $named $remote_fs $syslog
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
### END INIT INFO
PATH=/usr/local/sbin:/usr/local/bin:/sbin:/bin:/usr/sbin:/usr/bin
DAEMON=/usr/share/presto/bin/launcher
NAME=presto-server
DESC="Presto Server"
PIDFILE="/var/run/launcher.pid"

test -x $DAEMON || exit 0

set -e

case "$1" in
  start)
	echo -n "Starting $DESC: "
	$DAEMON start
	echo "$NAME."
	;;
  stop)
	echo -n "Stopping $DESC: "
        $DAEMON stop
	echo "$NAME."
	;;
  restart)
        echo -n "Restarting $DESC: "
        $DAEMON restart
        ;;
  status)
        echo -n "$DESC is "
	$DAEMON status
        ;;
  *)
	N=/etc/init.d/$NAME
	# echo "Usage: $N {start|stop|restart|status}" >&2
	echo "Usage: $N {start|stop|restart|status}" >&2
	exit 1
	;;
esac

exit 0
